### PR TITLE
Vault: `last_full_state_update_slot` and `last_fee_change_slot` should reflect the current slot

### LINKED ISSUE #108: Vault: `last_full_state_update_slot` and `last_fee_change_slot` should reflect the current slot
When initializing the vault, the current implementation sets `last_full_state_update_slot` to 0. However, I believe it should be initialized with the current slot. If it's set to 0, it creates an issue with the initialization of `vault_operator_delegation`, resulting in a `VaultError::VaultUpdateNeeded`.

### PR DESCRIPTION
**Pull request by aoikurokawa**
- Fixes #108

### CODE REVIEW

**Comment by aoikurokawa** [comment]
@buffalu @coachchucksol 
It's ready for review!

**Review by coachchucksol — APPROVED** [review]
Looks good to me. I don't feel there are any side effects here if we set it to the current slot upon creation. It looks like no actions are available to the vault until it's been updated - so this is a good qol improvement! 

@buffalu want to double check?

**Comment by buffalu** [comment]
one nit: can you add test check? after that lgtm

**Comment by aoikurokawa** [comment]
@buffalu @coachchucksol 
Thank you!! I added the test check!!

**Review by buffalu — APPROVED** [review]

**Pull request merged**
